# Generated by Django 4.2.25 on 2025-11-01 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name': 'product category', 'verbose_name_plural': 'product categories'},
        ),
        migrations.AlterField(
            model_name='product',
            name='specs',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='attributes',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
